/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDoLogger;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInfo;

import static org.junit.jupiter.api.Assertions.*;

import java.io.FileNotFoundException;
import java.io.IOException;

class AppTest {

    @BeforeEach 
    public void startTest(TestInfo testInfo) {
        System.out.printf("Starting %s: \n", testInfo.getDisplayName());
    }

    @Test 
    void getFileTest() throws IOException{
        Log loggerTest = new Log();
        assertEquals(loggerTest.getFile(), "Log.txt");
    }

    @Test 
    void readFileTest() throws FileNotFoundException, IOException{
        Log loggerTest = new Log();
        loggerTest.readFile("Log.txt");
    }

    @Test
    void checkDateTest() {
        Operations ops = new Operations();
        assertTrue(ops.checkDate("12/23/2020"));
    }
}
