/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDoLogger;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;

class AppTest {
    @Test void getFileTest() throws IOException{
        App loggerTest = new App();
        assertEquals(loggerTest.getFile(), "Log.txt");
    }


}
